### ISSUE TITLE
Decreased amount by more than 100 satoshi's

### ISSUE THREAD

**Issue by OpenGrid** [blockchain/My-Wallet-iPhone#36]
When iPhone wallet is used it sometimes sends an amount that is lower on average 100-150 satoshi from the amount requested in bitcoin: URI

**Comment by mpfluger** [comment]
We can't replicate this on our end. If you have an example URI or QR code, please post it here and re-open the issue.

**Comment by OpenGrid** [comment]
Excpected: 0.00489331
My-Wallet-iPhone interpretation: 0.00488404

**Comment by mpfluger** [comment]
Thanks for your comment, but we need either a URI or a QR code to verify that the information is not read correctly. Thanks!
