### ISSUE TITLE
URI handling

### ISSUE THREAD

**Issue by jgillard** [blockchain/My-Wallet-iPhone#37]
Bitcoin: links currently go to another app on my iPhone. Is URI handling supported?

**Comment by mpfluger** [comment]
URL handling is supported. If multiple applications are registered for the same URL handler, one will be chosen for you. According to Apple's documentation:

_Note: If more than one third-party app registers to handle the same URL scheme, there is currently no process for determining which app will be given that scheme._

https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html
