### ISSUE TITLE
What the app does after 3 false pin entry attempts?

### ISSUE THREAD

**Issue by orenyodfat** [blockchain/My-Wallet-iPhone#42]

**Comment by orenyodfat** [comment]
Does it erase the pin and ask for password?

**Comment by mpfluger** [comment]
Yes, after 3 failed attempts the PIN is reset and you will be asked for your password.

**Comment by orenyodfat** [comment]
Thanks,
I am prity sure that I know my pin code ...though the app did not accept
that..and get me to the password screen.
Is that a bug or known issue?

**Comment by mpfluger** [comment]
Hey,

I have been with Blockchain.info for over a year and worked on the iOS
wallet for some time during the last year. This would be the first time
I've heard that a correct PIN simply doesn't work. Please get in contact
with our support, they are very helpful and will try to assist you any
way they can.

Best,
  Mark
